library('googledrive')
```{r}
# The a wave is the colmination of 
# The c wave marks the start of the systole and represents the pressure rise inside the right atrium caused by the displacement of the tricuspid anulus ring

# I guess the a wave represents the atrium pushing the blood into the right ventricle 
# After that you have that fancy Tricuspidal Anulus movements leading to streching of the right atrium thus decresing its pressure (not sure about transmural yet, dont understand the concept for mow)
# Legalize it!
# pulse pressure has a lower and an upper end .. it is so far not clear what the notch in pulomnary artery pressure wave form means
```

```{r 25.12.23}

#### Cobalamin (70mg/kg) und 4-DMAP (3-4 mg/kg) können zusammen gegeben werden, jedoch 4-DMAP nicht bei Brandgasvergiftung -> dort Cobalamin (Cyanokit) mit O2
###
```

```{r}
# just realized that you can overline the pulmonary artery pressure graph and the central venus graph and allign waves and say fancy things that nobody understands

### 24.12.23
# Fröhliche Weihnachten
# The pulomonary artery pressure waveform can be understood as an combination of right ventricular wave superimposed on the left atrial waveform ... 
# the interesting part is that left atrial also has a and c waves!
```

### 24.12.23
# Fröhliche Weihnachten
# The pulomonary artery pressure waveform can be understood as an combination of right ventricular wave superimposed on the left atrial waveform ... 
# the interesting part is that left atrial also has a and c waves!

```{sql eval = FALSE}
-- first SQL code
select disposition, count(disposition) 
from `physionet-data.mimiciv_ed.edstays`
group by disposition
```

```{sql eval = FALSE}
-- count icd titles
select icd_title, count(icd_title) 
from `physionet-data.mimiciv_ed.diagnosis`
group by icd_title 
```

