---
title: "hyperoxia_stats"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/grigorijschleifer/Desktop/Hyperoxia-2020/data/")
```

```{r echo=FALSE, warning=FALSE, include=FALSE}
library(tableone)
library(sjPlot)
theme_set(theme_light())
```

```{r echo=FALSE, warning=FALSE, include=FALSE}
# write_csv(cohort_pao2, "~/Desktop/MIMIC_III/PT_Hyperoxia_2020/cohort_pao2.csv")
# write_csv(cohort_pao2_staged, "~/Desktop/MIMIC_III/PT_Hyperoxia_2020/cohort_pao2_staged.csv")
cohort_pao2 <- read_csv("~/Desktop/Hyperoxia-2020/data/report_data/cohort_pao2.csv")
```

```{r}
CreateCatTable(
    vars = c("aki_7day_new", "sofa"),
    strata = "two_oxy_level",
    data = cohort_pao2
)
# aki_7day_new = -2.71788 + (-0.64270 * two_oxy_level) 
uni_logistic <-
    glm(
        formula = aki_7day_new ~ two_oxy_level +  has_chronic_lung_conditions + sofa,
        data = cohort_pao2,
        family = binomial
    )
summary(uni_logistic)
tab_model(uni_logistic)

# mortality_30day
model <-
    glm(formula = hospmort30day ~ two_oxy_level,
        data = cohort_pao2,
        family = binomial)  tab_model(model) 
``` 
